# Generated by Django 5.1.2 on 2024-10-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0008_remove_apprenti_numero_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprenti',
            name='groupe',
        ),
    ]
