# Generated by Django 5.1.2 on 2024-10-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0012_remove_utilisateur_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenti',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
    ]
