# Generated by Django 5.1.2 on 2024-10-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0003_alter_customuser_date_of_birth'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatriceApprentissage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('prenom', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('prenom', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('intitule', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JournalDeFormation',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('date_derniere_modification', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TuteurPedagogique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('prenom', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Utilisateur',
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('capacite', models.IntegerField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_custom.formation')),
            ],
        ),
        migrations.CreateModel(
            name='MaitreApprentissage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('prenom', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
                ('entreprise', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_custom.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Apprenti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('prenom', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
                ('coordinatrice_apprentissage', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_custom.coordinatriceapprentissage')),
                ('groupe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_custom.groupe')),
                ('numero_journal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_custom.journaldeformation')),
                ('maitre_apprentissage', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_custom.maitreapprentissage')),
                ('tuteur_pedagogique', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_custom.tuteurpedagogique')),
            ],
        ),
    ]
