# Generated by Django 5.1.2 on 2024-10-17 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0004_coordinatriceapprentissage_enseignant_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenti',
            name='maitre_apprentissage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_custom.maitreapprentissage'),
        ),
    ]
