# Generated by Django 5.1.2 on 2024-10-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0007_remove_apprenti_coordinatrice_apprentissage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprenti',
            name='numero_journal',
        ),
    ]
