# Generated by Django 5.1.2 on 2024-10-18 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0010_utilisateur_tuteur_pedagogique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FicheDeSynthese',
            fields=[
                ('numero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_custom.journaldeformation')),
                ('date_publication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('numero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_custom.journaldeformation')),
                ('date_publication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RapportFinal',
            fields=[
                ('numero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_custom.journaldeformation')),
                ('date_publication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RapportPING',
            fields=[
                ('numero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_custom.journaldeformation')),
                ('date_publication', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='apprenti',
            name='coordinatrice_apprentissage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_custom.coordinatriceapprentissage'),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_custom.groupe'),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='maitre_apprentissage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_custom.maitreapprentissage'),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='numero_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_custom.journaldeformation'),
        ),
        migrations.AlterField(
            model_name='apprenti',
            name='tuteur_pedagogique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_custom.tuteurpedagogique'),
        ),
        migrations.CreateModel(
            name='EntretienSemestriel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('semestre', models.IntegerField()),
                ('note', models.FloatField()),
                ('commentaire', models.TextField()),
                ('apprenti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_custom.apprenti')),
                ('maitre_apprentissage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_custom.maitreapprentissage')),
                ('tuteur_pedagogique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_custom.tuteurpedagogique')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.FloatField()),
                ('commentaire', models.TextField()),
                ('apprenti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_custom.apprenti')),
                ('echeance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_custom.echeance')),
            ],
        ),
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('entretien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_custom.entretiensemestriel')),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_custom.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='MembreJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury', to='admin_custom.jury')),
                ('membre1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membre1', to='admin_custom.jury')),
                ('membre2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membre2', to='admin_custom.jury')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('echeance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_custom.echeance')),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.IntegerField()),
                ('note', models.FloatField()),
                ('commentaire', models.TextField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_custom.evaluation')),
            ],
        ),
    ]
