# Generated by Django 5.1.2 on 2024-10-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0011_admin_echeance_fichedesynthese_presentation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='tuteur_pedagogique',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='username',
        ),
        migrations.AlterField(
            model_name='apprenti',
            name='coordinatrice_apprentissage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.coordinatriceapprentissage'),
        ),
        migrations.AlterField(
            model_name='apprenti',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.groupe'),
        ),
        migrations.AlterField(
            model_name='apprenti',
            name='maitre_apprentissage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.maitreapprentissage'),
        ),
        migrations.AlterField(
            model_name='apprenti',
            name='numero_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.journaldeformation'),
        ),
        migrations.AlterField(
            model_name='apprenti',
            name='tuteur_pedagogique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.tuteurpedagogique'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.formation'),
        ),
        migrations.AlterField(
            model_name='maitreapprentissage',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.entreprise'),
        ),
    ]
