# Generated by Django 5.1.2 on 2024-10-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0014_fichesynthese_presentation_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FicheDeSynthese',
        ),
    ]
